import type { Metadata } from "next";
import ThemeRegistry from "./component/ThemeRegistry";
import "./globals.css";


export const metadata: Metadata = {
  title: "Next App MUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          {children}
        </body>
      </ThemeRegistry>
    </html>
  );
}